### PR TITLE
Fix for SvgUri and SvgCssUri crashing on non-existing svg files

### LINKED ISSUE #1500: SvgUri and SvgCssUri crash on URI not existing
When SvgUri or SvgCssUri load an URI that doesn't exist, it tries to parse the HTML error-page as SVG and crashes. The fetchText method in `node_modules/react-native-svg/src/xml.tsx` doesn't check for this condition.

### PR DESCRIPTION
**Pull request by SjaakSchilperoort**
# Summary

Fix for interpreting an HTML error response as svg data, and then crash when this cannot be parsed as well formed XML

closes #1500 

## Test Plan

n/a

### What's required for testing (prerequisites)?

Just a a clean project with the latest versions of react-native and react-native-svg

### What are the steps to reproduce (after prerequisites)?

Include this in App.js

```
<SvgUri width={100} height={100} uri={'https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/ruby.svg'} />
```
and you'll get:

Then make the file name invalid
```
<SvgUri width={100} height={100} uri={'https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/xruby.svg'} />
```
and you'll get:

With the fix you'll get this instead:

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    ✅     |
| Android |    ✅     |

## Checklist

- [ ] I have tested this on a device and a simulator
- [ ] I added documentation in `README.md`
- [ ] I updated the typed files (typescript)
- [ ] I added a test for the API in the `__tests__` folder

### CODE REVIEW

**Comment by jorgemasta** [comment]
Good catch! I think is a good improvement

**Comment by Ivanacc** [comment]
It would be great to add this fix! :)

**Comment by zrina1314** [comment]
why hasn't this library been updated for a long time

File: src/xml.tsx [hunk 1]
```diff
@@ -124,7 +124,7 @@ export function SvgXml(props: XmlProps) {
 
 export async function fetchText(uri: string) {
   const response = await fetch(uri);
-  return await response.text();
+  return response.ok ? await response.text() : null;
```
Comment (WoLewicki) [inline src/xml.tsx:127]: I think it would be good to add some message e.g. in a form of `console.warn` if the `response.ok` is `false`, so we could get information what went wrong. Then I think it is ready to be merged :tada:

Comment (SjaakSchilperoort) [reply src/xml.tsx]: Thanks, makes sense.

**Comment by WoLewicki** [comment]
I double-checked the code I think it would be even better to `throw Error` instead of `console.warn` there, since this method is used with `catch` in `SvgUri`, so the `Error` is caught and can be managed by the user in `onError` prop of `SvgUri`: https://github.com/react-native-svg/react-native-svg/blob/650275fdf5f0e3ff3fc51e8b2d8b98fd34110d1c/src/xml.tsx#L137. So such an example would work: 

```tsx
import React, {Component} from 'react';
import {  SvgUri } from 'react-native-svg';

class Example extends Component {

    state={
      uri: 'https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/xruby.svg',
    }

  render() {
    return (
      <>
        <SvgUri width={100} onError={err => this.setState({uri: 'https://dev.w3.org/SVG/tools/svgweb/samples/svg-files/ruby.svg'})} height={100} uri={this.state.uri} />
      </>
    );
  }
}
```

What do you think of it?

**Comment by WoLewicki** [comment]
I will also change the target branch since now `main` is the default branch to merge commits to.

**Comment by SjaakSchilperoort** [comment]
Yes, looks good.

Note that component `SvgCssUri`, which I use in my code, doesn't support property `onError`. I guess that adding support for this is a different issue.

**Comment by WoLewicki** [comment]
Yeah, I think it was missed in this commit: https://github.com/react-native-svg/react-native-svg/commit/3c32a6fdd580dea53ecc271288155117ce040b55. Could you make a PR with such change for `SvgCssUri`? I also checked where else `fetchText` is used and it looks like there is another place where it could be handled with `onError`: https://github.com/react-native-svg/react-native-svg/blob/54e40251a491bb1a2d0a75e4748a23ea24fb3f6b/src/LocalSvg.tsx#L58 Could you add same `.catch(err)` with an option of `onError` there too? It would then be handled everywhere then :tada: As for this PR, I think it is ready now so I'll merge it :tada: Thanks for your contribution.

**Comment by SjaakSchilperoort** [comment]
> Yeah, I think it was missed in this commit: https://github.com/react-native-svg/react-native-svg/commit/3c32a6fdd580dea53ecc271288155117ce040b55. Could you make a PR with such change for SvgCssUri?

See PR #1718

**Comment by CuriosBasant** [comment]
The `onError` prop on `SvgCssUri` doesn't work, it also shows ts error when using it.
