### PR TITLE
resolves On Android devices "getPointAtLength" function returns incorrect values

### LINKED ISSUE #1721: On Android devices "getPointAtLength" function returns incorrect values
# Bug

On Android devices "getPointAtLength" function returns incorrect values.

I have used `getPointAtLength` and passed in the output of `getTotalLength` expecting that I will get the end point on the path.
However on android I am getting some middle point on the path.
It works on ios devices. 

## Environment info

```bash
11:44 ~/priProject/CleanProject $ react-native info
info Fetching system and libraries information...
System:
    OS: macOS 12.2.1
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 3.85 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 14.17.6 - ~/.nvm/versions/node/v14.17.6/bin/node
    Yarn: 1.22.11 - ~/.nvm/versions/node/v14.17.6/bin/yarn
    npm: 6.14.15 - ~/.nvm/versions/node/v14.17.6/bin/npm
    Watchman: 2021.09.06.00 - /usr/local/bin/watchman
  Managers:
    CocoaPods: 1.11.0 - /usr/local/bin/pod
  SDKs:
    iOS SDK:
      Platforms: DriverKit 21.2, iOS 15.2, macOS 12.1, tvOS 15.2, watchOS 8.3
    Android SDK:
      API Levels: 28, 29, 30, 31
      Build Tools: 29.0.2, 29.0.3, 30.0.1, 30.0.2, 30.0.3
      System Images: android-28 | Google Play Intel x86 Atom, android-29 | Google Play Intel x86 Atom, android-30 | Google Play Intel x86 Atom
      Android NDK: Not Found
  IDEs:
    Android Studio: 4.0 AI-193.6911.18.40.6626763
    Xcode: 13.2.1/13C100 - /usr/bin/xcodebuild
  Languages:
    Java: 1.8.0_265 - /usr/bin/javac
  npmPackages:
    @react-native-community/cli: Not Found
    react: 17.0.2 => 17.0.2
    react-native: 0.67.3 => 0.67.3
    react-native-macos: Not Found
  npmGlobalPackages:
    *react-native*: Not Found
12:02 ~/priProject/CleanProject (master)$
```

Library version: 12.3.0

## Steps To Reproduce
1. git clone https://github.com/insbodhi/RNSvgGetPointBugAndroid.git
2. cd RNSvgGetPointBugAndroid
3. npm install
4.  npm run android

Describe what you expected to happen:

1. I am expecting to see following screen
image

3. however I see
image

The circle on orange line should be placed at the end of line as 'cx' and 'cy' values for this circle are calculated using `getPointAtLength(length)` where length is total length of the path which is calculated using  `getTotalLength`

### PR DESCRIPTION
**Pull request by insbodhi**
# Summary

This pull request resolves #1721. While computing the  point at length I have passed in the scaled value for  path length.

## Compatibility

| OS      | Implemented |
| ------- | :---------: |
| iOS     |    no change required     |
| Android |    ✅    |

## Checklist

- [X] I have tested this on a device and a simulator
- [ ] I added documentation in `README.md`
- [ ] I updated the typed files (typescript)
- [ ] I added a test for the API in the `__tests__` folder

### CODE REVIEW

**Comment by NamithaRavy** [comment]
Hi Team,
I found this solution useful. Please merge this PR.

File: android/src/main/java/com/horcrux/svg/RNSVGRenderableManager.java [hunk 1]
```diff
@@ -111,20 +111,13 @@ public WritableMap getPointAtLength(int tag, ReadableMap options) {
 
     Path path;
```
Comment (WoLewicki) [inline android/src/main/java/com/horcrux/svg/RNSVGRenderableManager.java:113]:
```suggestion

    try {
      path = svg.getPath(null, null);
    } catch (NullPointerException e) {
      svg.invalidate();
      return Arguments.createMap();
    }

```

**Review by WoLewicki — APPROVED** [review]
The changes look good! Thanks for your contribution :tada:
